Return-Path: <donotreply@interactivebrokers.com>

Received: from perlnow.com [64.62.154.102]

	by tiny.mylan.org with POP3 (fetchmail-6.3.18)

	for <d@perlnow.com> (single-drop); Tue, 21 Feb 2012 11:17:26 -0500 (EST)

Received: from mx1.interactivebrokers.com ([206.106.137.9]) by perlnow.com for <ib@perlnow.com>; Tue, 21 Feb 2012 08:16:47 -0800

Received: from gw100.interactivebrokers.com (gw100.interactivebrokers.com [206.106.137.7])

	by mx1.interactivebrokers.com (Sentrion-MTA-4.2.2/Sentrion-MTA-4.2.2) with ESMTP id q1LGGkAk028465

	(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-SHA bits=256 verify=NO)

	for <ib@perlnow.com>; Tue, 21 Feb 2012 11:16:46 -0500

DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple;

	d=interactivebrokers.com; s=Feb2011; t=1329841006;

	bh=XN6Xw5b4UaQs/camXOg0FuYFCiDDYxKhNRAgni04BLY=;

	h=Date:Message-ID:From:To:Subject:Mime-Version:Content-Type;

	b=ReXRdsaalQ+dX44C+Kffhjh/uNARBpGwrVFRhUHlOZpQUq8yljFpRF/OwrCrEld1r

	 COep13cLAmfaJL1eMBKUULO8ntZI5BPug7X/j8l7JtFhPbY6bs9RjOSRECm0bDbO29

	 ETjuTMaHER/ZXwtrq7eATnQmcMmjswRQBx8i8oKA=

X-DKIM: OpenDKIM Filter v2.1.3 mx1.interactivebrokers.com q1LGGkAk028465

Received: from ibmkt2 (ibmkt2 [192.9.217.153])

	by gw100.interactivebrokers.com (8.13.8/8.13.8) with ESMTP id q1LGGkh0002787

	for <ib@perlnow.com>; Tue, 21 Feb 2012 11:16:46 -0500

Date: Tue, 21 Feb 2012 11:16:46 -0500

Message-ID: <31131496.1329841006124.JavaMail.csprod@ibmkt2>

From: Interactive Brokers Customer Service <donotreply@interactivebrokers.com>

To: ib@perlnow.com

Subject: Message from IB

Mime-Version: 1.0

Content-Type: multipart/alternative; 

	boundary="----=_Part_1170040_19816077.1329841006094"

X-Priority: 3

X-Copied: Archived



------=_Part_1170040_19816077.1329841006094

Content-Type: text/plain; charset=UTF-8; format=flowed

Content-Transfer-Encoding: 7bit



ALERT: UXXX973 SOLD RY 100@53.5 as of 2012-02-24 11:16:38

------=_Part_1170040_19816077.1329841006094--


